apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintain-kubeusers
  labels:
    app: maintain-kubeusers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintain-kubeusers
  template:
    metadata:
      labels:
        app: maintain-kubeusers
    spec:
      serviceAccountName: user-maintainer
      nodeSelector:
        kubernetes.wmcloud.org/nfs-mounted: "true"
      volumes:
      - name: my-host-project
        hostPath:
          path: /data/project
          type: Directory
{{ if .Values.mountHome }}
      - name: my-host-home
        hostPath:
          path: /home
          type: Directory
{{ end }}
      - name: my-host-etc-ldap
        hostPath:
          path: /etc/ldap.yaml
          type: File
      containers:
      - name: maintain-kubeusers
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command: {{ .Values.image.command | toJson }}
        args: {{ .Values.image.args | toJson }}
        volumeMounts:
        - mountPath: /data/project
          name: my-host-project
{{ if .Values.mountHome }}
        - mountPath: /home
          name: my-host-home
{{ end }}
        - mountPath: /etc/ldap.yaml
          name: my-host-etc-ldap
{{ if .Values.enableLivelinessProbe }}
        livenessProbe:
          exec:
            command:
            - find
            - /tmp/run.check
            - -mmin
            - '+5'
            - -exec
            - rm
            - /tmp/run.check
            - ;
          initialDelaySeconds: 5
          periodSeconds: 5
{{ end }}
        ports:
          - containerPort: 9000
            name: metrics
            protocol: TCP
