# You must have deployed one of the kustomize-based ./deployments directories
# for this to be a working pod.
apiVersion: v1
kind: Pod
metadata:
  name: maintain-kubeusers-ops
  namespace: maintain-kubeusers
  labels:
    ops: maintain-kubeusers
spec:
  serviceAccountName: user-maintainer
  volumes:
  - name: my-host-project
    hostPath:
      path: /data/project
      type: Directory
  - name: my-host-home
    hostPath:
      path: /home
      type: Directory
  - name: my-host-etc-ldap
    hostPath:
      path: /etc/ldap.yaml
      type: File
  containers:
  - name: maintain-kubeusers
    image: docker-registry.tools.wmflabs.org/maintain-kubeusers:latest
    command: ["/bin/ash"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    volumeMounts:
    - mountPath: /data/project
      name: my-host-project
    - mountPath: /home
      name: my-host-home
    - mountPath: /etc/ldap.yaml
      name: my-host-etc-ldap
