# this is for local development
image:
  name: maintain-kubeusers
  tag: latest
  pullPolicy: Never
  args: ["/app/maintain_kubeusers.py", "--project=toolsbeta", "--debug"]

mountHome: false
enableLivelinessProbe: false
includeBaseRbac: false
